name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  buildpush:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Docker image for data
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./data_manager/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/big_data_data:latest

    - name: Build and Push Docker image for webapp
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./webapp/Dockerfile
        push: true
        tags:  ${{ secrets.DOCKERHUB_USERNAME }}/big_data_webapp:latest